import React, { useState } from 'react';
import {
  Accordion,
  AccordionBody,
  AccordionHeader,
  AccordionItem,
} from 'reactstrap';

function Acordion(props) {
  const [open, setOpen] = useState('');
  const toggle = (id) => {
    if (open === id) {
      setOpen();
    } else {
      setOpen(id);
    }
  };

  return (
    <div>
      <Accordion flush open={open} toggle={toggle}>
        <AccordionItem>
          <AccordionHeader targetId="1">Origenes</AccordionHeader>
          <AccordionBody accordionId="1">
            <p>La historia se remonta cuando dos miembros de la Iglesia de St. Marks, que trabajaban en una fábrica de hierro al este de Mánchester; y Anna Connell, hija del rector Arthur Connell, fundaron el St. Mark's, con fines principalmente humanitarios.</p>
            <p>Como la mayoría de las áreas industriales de rápido crecimiento del norte y la región central, West Gorton no tenía instalaciones sociales aparte de los bares. Anna y dos guardias de la iglesia trataron de frenar la violencia de las pandillas locales y el alcoholismo instituyendo nuevas actividades para los hombres locales, mientras que el alto desempleo asolaba el este de Manchester, específicamente Gorton. Todos los hombres eran bienvenidos a unirse, sin importar su religión.</p>
            <p>En 1875 se había formado un club de cricket en la iglesia, pero no existía ningún equivalente para los meses de invierno.8​ Para rectificar esto, y como parte del impulso general del rector Arthur Connell para intervenir en los males sociales, Anna Connell y los guardianes de la iglesia William Beastow y Thomas Goodbehere, que ocupaban altos cargos en la Union Iron Works,9​ crearon un equipo de fútbol de la iglesia llamado St Mark's (West Gorton) -a veces escrito como West Gorton (St Mark's)- en el invierno de 1880.</p>
            <p>El primer partido registrado del equipo ocurrió el 23 de noviembre de 1880, contra un equipo de la iglesia de Macclesfield. St. Marks perdió el partido 2-1, y sólo ganó un encuentro durante su temporada inaugural de 1880-81, con una victoria sobre Stalybridge Clarence en marzo de 1881.</p>
            <p>En 1887 el club se traslada a un nuevo campo en Hyde Road (antes un vertedero) y pasó a llamarse Ardwick A.F.C para reflejar su nueva localización. El Ardwick se unió a la Liga de Fútbol inglesa como miembros fundadores de la Second Division en 1892. Finalmente, problemas financieros en la temporada 1893-1894 le llevaron a realizar una completa reestructuración que afectó a todos los aspectos de la institución, pasando así a llamarse Manchester City Football Club.</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="2">Debut profesional</AccordionHeader>
          <AccordionBody accordionId="2">
           <p>El City obtuvo éxitos importantes en sus primeros años. Logró el ascenso a la First Division —máxima categoría por aquel entonces— en la temporada 1898-1899. Su primer título oficial lo ganó el 23 de abril de 1904, al vencer en la final de la FA Cup —Copa de Inglaterra— al Bolton Wanderers en Crystal Palace National Sports Centre; esa misma temporada el club estuvo cerca de ganar el título de liga, pero finalizó segundo. Pese a eso, se convirtió en el primer club de Mánchester en ganar un título oficial.10​ En las temporadas siguientes al triunfo en la FA Cup, el club se vio afectado por irregularidades financieras, que culminaron con la suspensión de diecisiete jugadores en 1906, entre ellos el capitán Billy Meredith, que posteriormente pasó a jugar para el Manchester United.11​ Un incendio en Hyde Road en 1920 destruyó la grada principal, por lo que en 1923 el club se trasladó a su nuevo estadio Maine Road.</p>
           <p>En los años 1930, el Manchester City llegó a dos finales consecutivas de la FA Cup, perdiendo ante el Everton en 1933 y ganando al Portsmouth en 1934. Cabe destacar que durante dicha FA Cup, el Manchester City estableció el récord de asistencia más alta de cualquier club en la historia del fútbol inglés, ya que 84 569 aficionados llenaron Maine Road para la sexta ronda eliminatoria de la competición ante el Stoke City, récord que sigue vigente hasta la actualidad.12​ En la temporada 1936-1937, ganó por primera vez el título de liga, aunque en la temporada siguiente el equipo descendió a Second Division, pese a haber sido el club con más goles a favor en esa temporada.13​ Veinte años más tarde, el City utilizó un sistema táctico innovador, conocido como «Plan Revie», con lo que el club llegó nuevamente a dos finales consecutivas de la FA Cup, en 1955 y 1956; y al igual que en la década de 1930, perdió la primera, ante el Newcastle United, y ganó la segunda. La Final de la FA Cup de 1956, en la que el Manchester City venció al Birmingham City por 3-1, es una de las finales más famosas de todos los tiempos, y es recordada porque el portero Bert Trautmann jugó sin saber que tenía el cuello roto.</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="3">La época de oro y años 1970</AccordionHeader>
          <AccordionBody accordionId="3">
            <p>Tras el descenso a la Second Division en 1963, el futuro del club parecía oscuro, ya que, entre otras cosas, sucedió el registro de asistencia en un partido como local más bajo en toda la historia del club ante el Swindon Town, con la presencia de 8015 espectadores en enero de 1965.15​ En mitad de la temporada, fue contratado un nuevo equipo técnico formado por Joe Mercer como entrenador y Malcolm Allison como asistente. En la primera temporada bajo las órdenes de Mercer, el club terminó la temporada de la Second Division como campeón, y realizó una fuerte inversión en jugadores como Mike Summerbee y Colin Bell.16​ Dos temporadas después, en la 1967-1968, el Manchester City logró su segundo título de liga, al vencer en el último partido de la temporada al Newcastle United por 4-3 y relegando a su vecino el Manchester United al subcampeonato.17​ Los títulos siguieron en estos años: en 1969 obtuvo su cuarta FA Cup ganando la final al Leicester City, obteniendo una plaza para participar en la Recopa de Europa 1969-1970, en la que el club inglés se impuso en la final ante el Górnik Zabrze de Polonia por 2-1 en Viena.18​ Este sería el primer título del Manchester City a nivel europeo. El club ganó en esa misma temporada la Copa de la Liga, convirtiéndose en el segundo club inglés en ganar un título internacional y uno nacional en la misma temporada.</p>
            <p>El club continuó luchando por títulos en el fútbol nacional, terminando un punto por detrás de los campeones de liga en dos ocasiones y proclamándose subcampeón de la Copa de la Liga en 1974.19​ Uno de los partidos más recordados por los aficionados es el último partido de la temporada de Liga 1973-1974, ante el Manchester United, que necesitaba ganar para eludir el descenso a la Second Division. El exjugador del United Denis Law anotó con el talón para el triunfo 0-1 del City y confirmar el descenso del Manchester United.20​ El último título de esta época de éxito fue en 1976, al derrotar a Newcastle United 2-1 en la final de la Copa de la Liga.</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="4">Declive, crisis financiera y reconstrucción</AccordionHeader>
          <AccordionBody accordionId="4">
           <p>Un largo período de declive siguió al éxito de los años 1960 y 1970. Malcolm Allison se reincorporó al club para convertirse en gerente, por segunda vez en 1979, pero desperdició grandes sumas de dinero en fichajes fallidos, como el Steve Daley.21​ El club llegó a tener siete gerentes solamente en la década de 1980, bajo la dirección técnica de John Bond, el City llegó a la final de la FA Cup de 1981, que acabaría perdiendo en el partido de desempate ante el Tottenham Hotspur. El club descendió dos veces de la máxima categoría en la década de 1980 (en 1983 y 1987), pero regresó de nuevo en 1989. Finalizó quinto en las temporadas 1990-1991 y 1991-1992 bajo la dirección de Peter Reid.22​ El club fue uno de los miembros fundadores de la Premier League en 1992. Tras la salida de Reid, el Manchester City decayó, ya que pasó tres temporadas peleando por no descender a la segunda categoría —ahora llamada First Division, algo que finalmente se concretó en 1996. El Manchester City cayó al punto más bajo de su historia al descender a la tercera categoría del fútbol inglés en la temporada 1997-1998 —llamada, desde 1992, Second Division— siendo el segundo equipo con títulos europeos en descender a esta categoría, después de que en Alemania se concretara unos años antes el descenso de 1. FC Magdeburg.</p>
           <p>Tras el descenso, llegó un nuevo presidente, David Bernstein, que introdujo cambios importantes en el club, entre ellos una nueva política económica.23​ Con la dirección técnica de Joe Royle, el Manchester City logró ascender en su primer intento tras vencer en los playoff al Gillingham. Estando ya en segunda división, un segundo ascenso consecutivo vio al club ascender a la Premier League, pero esto resultó haber sido un paso demasiado apresurado para la estabilización del club, y en consecuencia, en 2001, el club volvió a descender a la segunda categoría. Para la siguiente temporada, es contratado Kevin Keegan como nuevo entrenador, y el equipo lograría ascender como campeón obteniendo 99 puntos y 108 goles a favor durante la temporada, logrando el ascenso inmediato.24​ La temporada 2002-03 fue la última que se jugaría en Maine Road, que incluyó una victoria de 3-1 ante sus rivales del Manchester United, poniendo fin a una racha de 13 años sin ganar. Esa misma temporada se clasificó para competiciones europeas después de 25 años a través del Ranking de Fair Play de la UEFA.25​ En la temporada 2003-04, el club se trasladó al Estadio Ciudad de Mánchester, inaugurado en verano en un amistoso frente al FC Barcelona.26​ En sus cuatro primeras temporadas en el nuevo estadio, el club finalizó en la mitad de tabla o en los puestos cercanos al descenso, lo que acabó provocando la renuncia de Kevin Keegan en 2005.27​ El exentrenador de la selección inglesa de fútbol, Sven-Göran Eriksson se convirtió en el primer extranjero en dirigir al club, al ser contratado en 2007. Un año después, en julio de 2008, el sueco fue despedido y reemplazado por Mark Hughes.28</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="5">Llegada de la inversión de Emiratos Árabes Unidos</AccordionHeader>
          <AccordionBody accordionId="5">
            <p>En el año 2008, el club estaba en una precaria situación financiera. Thaksin Shinawatra, ex primer ministro de Tailandia, había comprado el club un año antes tras abonar 121 millones de euros,29​ pero sus afanes políticos veían sus activos congelados, además de ser acusado en su país de corrupción y lavado de dinero.30​ Sin embargo, el 1 de septiembre de 2008, Abu Dhabi United Group for Development and Investment, un grupo inversor de Emiratos Árabes Unidos (EAU), con Sulaiman Al-Fahim como parte visible del grupo, y con Mansour bin Zayed Al-Nahyan como máximo accionista, se hizo con el control del club por 250 millones de euros.31​ La compra fue seguida inmediatamente por un aluvión de ofertas por jugadores de alto perfil. El club rompió el récord de transferencia británica mediante el fichaje de Robinho del Real Madrid por unos 40 millones de euros,32​ en lo que sería el preludio de la astronómica inversión en fichajes que vendría para situar al equipo entre los grandes de Europa.33​ Sin embargo, las actuaciones del club no mostraban mejoras con respecto a la campaña anterior a pesar de la afluencia de dinero, sin embargo, pese a acabar décimo en la Premier League,34​ el club alcanzó los cuartos de final de la Copa de la UEFA.</p>
            <p>Durante el verano de 2009, el club realizó un gasto en fichajes a un nivel sin precedentes, con un desembolso de más de 150 millones de euros para la contratación de jugadores como Gareth Barry, Roque Santa Cruz, Kolo Touré, Emmanuel Adebayor, Carlos Tévez y Joleon Lescott. En diciembre de 2009, con el equipo como 6.º clasificado tras 18 jornadas, Mark Hughes, que entrenaba al Manchester City desde hacia poco antes de la llegada del grupo inversor árabe, fue destituido como entrenador y en su lugar se contrata a Roberto Mancini.35​ El City acabó la temporada en quinta posición de la Premier League, clasificándose para disputar la Copa de la UEFA (renombrada ahora como Liga Europa de la UEFA).36​</p>
            <p>La inversión continuó en las temporadas sucesivas, y los resultados empezaron a coincidir con el repunte de la calidad de los jugadores.37​38​39​ El Manchester City llegó a la Final de la FA Cup de 2011 tras derrotar en semifinales al Manchester United. Derrotó 1-0 al Stoke City en la final ganando su quinta FA Cup40​ y su primer título oficial en Inglaterra desde 1976. Esa misma semana certificaba su clasificación, después de 43 años, para la Liga de Campeones de la UEFA 2011-2012 tras ganar 1-0 al Tottenham Hotspur.41</p>
            <p>Las grandes actuaciones continuaron en la temporada siguiente, derrotando 1-5 al Tottenham Hotspur en su estadio, y humillando al Manchester United por un marcador de 1-6.42​ El 13 de mayo de 2012 gana, después de 43 años, el título de Premier League (tercero en su palmarés) a su eterno rival, el United, luego de recortar una desventaja de ocho puntos en la tabla. En el último partido de liga tuvieron que remontar marcando dos goles en el descuento contra el Queens Park Rangers en un épico final, con un gol de Edin Džeko (el 2-2) y el gol definitivo marcado por el delantero argentino Sergio Agüero (el definitivo 3-2) haciéndoles campeones.43</p>
            <p>La temporada 2012-2013 fue bastante decepcionante. Comenzó ganando la Community Shield al Chelsea,44​ siendo este el único título de la temporada. El City fracasó en la Liga de Campeones, ya que fue eliminado en la fase de grupos sin ganar ningún partido,45​ no revalidó el título de campeón de la Premier League y perdió la final de la FA Cup ante el Wigan.46​ El 13 de mayo, dos días después de perder la final, la directiva optó por despedir a Roberto Mancini.47​ Le sustituyó el segundo entrenador Brian Kidd para dirigir los dos últimos partidos de liga, certificando el subcampeonato.</p>
            <p>En la temporada 2013-2014 se fichó como entrenador a Manuel Pellegrini.48​ El City comenzó la Premier League con algunos problemas en los partidos jugados fuera de casa, siendo derrotado por rivales teóricamente muy inferiores como el Cardiff City o el Aston Villa; pero en cambio se mostraba intratable en su estadio, donde goleó al Tottenham Hotspur (6-0), Manchester United (4-1) y al Arsenal (6-3).49​ Finalmente el equipo encuentra la regularidad y termina la primera vuelta en segundo puesto,50​ al tiempo que consigue el pase a octavos de final de la Liga de Campeones de la UEFA 2013-14 por primera vez en su historia.51​ El 2 de marzo, consigue ganar la Copa de la Liga al derrotar al Sunderland en la final por 3-1;52​ pero diez días después, es eliminado de la Liga de Campeones por el Barcelona.53​ Como colofón a la temporada, el equipo logra su cuarto título de campeón de la Premier League en la última jornada, tras recortar 6 puntos de ventaja al Liverpool.5</p>
            <p>Pellegrini se despidió del Manchester City tras obtener la Copa de la Liga y el 4.º puesto en la Premier League en la temporada 2015-16.55​</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="6">Escudo</AccordionHeader>
          <AccordionBody accordionId="6">
            <p>El actual escudo del equipo fue agregado oficialmente el 3 de julio de 2016 durante el Cityzens Weekend siendo adoptado en la temporada 2016-2017. El nuevo símbolo está inspirado en los escudos clásicos que habían representado a los "citizens" durante su historia. La elección del nuevo diseño fue realizada a través de una encuesta entre los aficionados que acudían al Etihad Stadium, que manifestaron haberlo elegido porque es el más representativo para el club siendo a su vez moderno y original.</p>
            <p>El mayor cambio es que el diseño es circular, como ha sido en dos de los tres últimos escudos. El escudo es dominado por el azul (94 %) y blanco (68 %). Siendo los dos colores más populares. El escudo posee tres símbolos. La nave de Manchester (85 %) que aparece en los tres escudos anteriores del Club. Los tres ríos (67 %) El Irwell, Medlock e Irk son el alma de la ciudad, y aparecen en dos de las tres insignias anteriores del Club. La rosa roja (60 %) simboliza la herencia histórica del Club y su conexión con Lancashire. Los tres símbolos están contenidos en una versión evolucionada en el escudo actual, que es más grande y cuenta con un plano superior. El escudo se ve tocando el anillo exterior para traer modernidad a toda la insignia y permitir que el escudo sea reconocible como un símbolo.Manchester y City son visibles en la parte de afuera del texto, en un anillo exterior blanco como aparece en la última insignia del Club. Finalmente el año de fundación del Club, 1894, es incluido por primera vez, en recordatorio a la herencia y la constancia del Club.</p>
            <p>El escudo que el Manchester City utilizó hasta la temporada 2015-2016 fue adoptado en 1997, como resultado de que el escudo anterior era imposible de registrarlo como marca. El escudo se basa en el escudo de armas de Mánchester y está formado por un águila real. El águila es un antiguo símbolo heráldico de la ciudad de Mánchester. Fue introducida al escudo del club un águila de oro en 1958 (pero ya se ha eliminado), en representación de la creciente industria de aviación. El escudo cuenta con un barco en su mitad inferior que representa el canal de Mánchester y tres franjas blancas diagonales en su mitad inferior que simbolizan los ríos Irwell, Irk y Medlock. Debajo del escudo, lleva una cinta con el lema en latín Superbia in Proelio, 'Orgullo en la batalla'. Por encima del águila real, lleva tres estrellas que son puramente decorativas.</p>
            <p>El City ha tenido otros escudos: el primero, presentado en 1970, se basó en los diseños que se habían utilizado en la documentación oficial del club desde mediados de 1960; consistía en una placa circular que utilizaba el mismo escudo actual, dentro de un círculo que llevaba el nombre del club. En 1972, fue cambiado por una variación que sustituyó la parte inferior del escudo por la rosa roja de Lancashire.</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="7">Estadio</AccordionHeader>
          <AccordionBody accordionId="7">
            <p>El estadio donde el Manchester City juega sus partidos como local es el Etihad Stadium, llamado así por razones de patrocinio,86​ situado al este de la ciudad, inaugurado durante los Juegos de la Mancomunidad de 2002, y en el que el club juega desde la temporada 2003-04. Cuenta con capacidad para 53 400 personas. Antes de trasladarse al nuevo estadio se acometieron reformas para adaptar el terreno a un campo de fútbol. El partido inaugural del nuevo estadio fue ante el FC Barcelona con victoria para el City por 2-1.87​88​ Durante el verano de 2011, el club alcanzó un acuerdo con la aerolínea Etihad Airways para que el estadio llevara su nombre.89​</p>
            <p>A lo largo de su historia, el Manchester City ha jugado en otros terrenos. Tras jugar en cinco campos diferentes entre 1880 y 1887, el equipo se marchó a Hyde Road, estadio en el que jugó durante 36 años hasta que en 1920 un incendio destruyó la grada principal.90​ En 1923, el equipo se marcha a un estadio con capacidad para 84 000 personas,91​ Maine Road, que fue calificado por sus diseñadores como el Wembley del Norte. El campo sufrió diferentes remodelaciones para adaptar el aforo a la normativa europea, quedando finalmente en 32 000 espectadores. En él jugó hasta 2003.</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="8">Entrenadores</AccordionHeader>
          <AccordionBody accordionId="8">
           <p>Durante mucho tiempo, el club sólo tuvo entrenadores británicos. En 2007, el sueco Sven-Göran Eriksson se convirtió en el primer entrenador del Manchester City procedente de fuera del Reino Unido. Las nacionalidades principales de los entrenadores no ingleses han sido la escocesa (6 técnicos), sueca (1 técnico), italiana (1 técnico), galesa (1 técnico), chilena (1 técnico) y española (1 técnico).

1880-1882 Bandera de Inglaterra Frederick Hopkinson
1882-1884 Bandera de Irlanda Jack MCGee
1884-1887 Bandera de Inglaterra Edward Kitchen
1887-1889 Bandera de Inglaterra Walter Chew
1889-1893 Bandera de Inglaterra Lawrence Furniss
1893-1895 Bandera de Inglaterra Joshua Parlby
1895-1902 Bandera de Inglaterra Sam Omerod
1902-1906 Bandera de Inglaterra Tom Maley
1906-1912 Bandera de Inglaterra Harry Newbould
1912-1924 Bandera de Inglaterra Ernest Mangnall
1924-1925 Bandera de Inglaterra David Ashworth
1925-1926 Bandera de Inglaterra Albert Alexander
1926-1932 Bandera de Escocia Peter Hodge
1932-1946 Bandera de Inglaterra Wilf Wild
1946-1947 Bandera de Inglaterra Sam Cowan
1947 Bandera de Inglaterra Wilf Wild
1947-1950 Bandera de Escocia Jock Thomson
1950-1963 Bandera de Escocia Les McDowall
1963-1965 Bandera de Inglaterra George Poyser
1965-1971 Bandera de Inglaterra Joe Mercer
1971-1973 Bandera de Inglaterra Malcolm Allison
1973 Bandera de Inglaterra Johnny Hart
1973 Bandera de Inglaterra Tony Book
1973-1974 Bandera de Inglaterra Ron Saunders
1974-1979 Bandera de Inglaterra Tony Book
1979-1980 Bandera de Inglaterra Malcolm Allison</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="9">Afición</AccordionHeader>
          <AccordionBody accordionId="9">
            <p>El Manchester City cuenta con una de las aficiones más fanáticas y apasionadas de Inglaterra.115​ Son popularmente conocidos como los Cityzens, Sky Blues, o, más correctamente, Blues. La prensa suele preferir el apelativo Sky Blue para distinguirlos de otros clubes como el Chelsea, que también usa el mismo sobrenombre; pero los seguidores y los mismos mancunianos en general se refieren a sí mismos como Blues, ya que en sí no hay otro club en Mánchester que vista de azul. Han demostrado su extraordinaria lealtad al club durante los años más difíciles, incluso cuando el club descendió dos veces en tres temporadas y jugaba en la tercera categoría del fútbol inglés (por aquel momento Division Two, ahora English Football League One), el promedio del City fue de 30 000 por partido, comparado con el promedio de la categoría de menos de 8000 espectadores.116​ Desde que se mudó al Estadio Ciudad de Mánchester, el promedio del City ha estado entre los seis primeros en Inglaterra, generalmente superando los 40 000 espectadores. Una investigación llevada a cabo por el Manchester City en 2005 estima una base de fanes de 886 000 en el Reino Unido y un total de más de 2 millones en todo el mundo, aunque desde la compra del club por Sheikh Mansour y los trofeos recientes del club, esa cifra ha incrementado varias veces esa cantidad.117​</p>
            <p>Los seguidores del Manchester City se distinguen por su azul celeste, un color que solo utilizan unos pocos clubes del fútbol profesional en Inglaterra. La canción elegida por los aficionados del City es una versión "Blue Moon", que a pesar de su tema melancólico es cantada con gran entusiasmo por la afición como si se tratara de un himno heroico. El historiador y escritor Gary Milton James dijo que la primera vez que escuchó cantar Blue Moon por los fanáticos del City fue en la temporada 1989-90, luego de perder contra Liverpool en Anfield. Tres hinchas empezaron a cantar la canción de forma melancólica saliendo del estadio. La canción encajó muy bien con el City por los años que pasó el club, y también por los colores y hoy es parte de la historia del equipo.</p>
            <p>A fines de la década de 1980, los fanáticos del City comenzaron la locura de llevar objetos inflables a los partidos, principalmente plátanos de gran tamaño.118​ Una explicación controvertida de la locura es que en un partido contra West Bromwich Albion los cánticos de los fanáticos que pedían la introducción de Imre Varadi, que se convirtió en "Imre Banana". Las terrazas repletas de aficionados que agitaban inflables se convirtieron en un espectáculo frecuente en la temporada 1988-89, cuando la locura se extendió a otros clubes (se vieron peces inflables en Grimsby Town), y el fenómeno alcanzó su punto máximo en el partido del City contra el Stoke City, el 26 de diciembre de 1988, un partido declarado por como fiesta de disfraces. La visión se había extendido a través de los medios de comunicación, con numerosos informes de BBC News a lo largo de la temporada comentando sobre moda, elogiando cómo "devolver la diversión al fútbol". En una entrevista con el entonces secretario del Manchester City, Bernard Halford, dando un 'ok' al director, declaró "Devolver la diversión al juego... y acabar con los hooligans se trata de todo". En 2010, los seguidores adoptaron un baile exuberante, apodado The Poznań, de los fanes del club polaco Lech Poznań.</p>
            <p>El Manchester City tiene el segundo récord de asistencia más alto en el fútbol inglés (84 569), solo superado por el Tottenham F. C. el 14 de septiembre de 2016, cuando los Spurs jugaban temporalmente partidos de local en el estadio de Wembley por la Liga de Campeones. Sin embargo, el Manchester City todavía tiene el récord del partido de fútbol inglés con mayor asistencia, 84 569 fanáticos llenaron Maine Road para una eliminatoria de la FA Cup, en la sexta ronda contra Stoke City en 1934 (el City ganó la FA Cup esa temporada).120​ El terreno se había llenado dos horas y media antes del inicio del partido, ya que los aficionados se sentaron en la línea de banda a solo unos metros del portero Frank Swift y la magnitud de la multitud provocó una avalancha, causando algunas lesiones.</p>
          </AccordionBody>
        </AccordionItem>
        <AccordionItem>
          <AccordionHeader targetId="10">En la cultura popular</AccordionHeader>
          <AccordionBody accordionId="10">
            <p>El Manchester City también es conocido por sus distinguidos fanáticos, los más notorios son los hermanos Liam y Noel Gallagher. Los exlíderes del desaparecido grupo Oasis son tan fanáticos del City que se han negado repetidamente a actuar en el estadio de Old Trafford, hogar del archirrival Manchester United. En el apogeo de su éxito, en 1996, tocaron en el entonces estadio de su equipo, Maine Road, en la primera etapa de la gira que promocionaría el álbum (What's the Story) Morning Glory?, en un show que fue oficialmente grabado y lanzado en vídeo con el nombre Debut at Maine Road. En la portada, los Gallagher aparecen vistiendo las camisetas del City. Además de esto, son vistos en numerosas ocasiones asistiendo a distintos partidos del club, y también han colaborado en varias campañas publicitarias de equipaciones nuevas, como Liam Gallagher hizo en la 11/12121​o Noel Gallgaher en la siguiente temporada 122​. Además, según narra el libro Getting High (1997)123​ de Paolo Hewitt, bajo la presidencia de Mike Summerbee en los 90 (y coincidiendo con el pico de fama de Oasis), se propuso personalizar las camisetas del equipo con el nombre del grupo, sin embargo, esto nunca llegó a materializarse. No obstante, ha sido recientemente publicado en prensa que se planea que la marca del grupo colabore para el diseño de una de las camisetas en la temporada 24/25124​, coincidiendo con el 30 aniversario del disco debut de la banda Definitely Maybe (1994).</p>
            <p>Otros dos músicos de culto, uno ya fallecido, ambos de otras dos célebres bandas de la ciudad, también son recordados como seguidores del club: el primero de ellos se trata de Ian Curtis, líder de Joy Division, donde su preferencia por los Sky Blues se reveló en su biografía, Control. El otro es Johnny Marr, ex guitarrista de The Smiths. Además, otros fanáticos del equipo son: otro exmiembro de The Smiths, el baterista Mike Joyce; el líder de The Fall, Mark E. Smith; y el tecladista Rick Wakeman, consagrado al rock progresivo.</p>
            <p>Manchester City F.C. y sus fans han sido retratados en numerosos programas de televisión, arte y música. L. S. Lowry era un seguidor del Manchester City que se inspiró en su gente, a menudo conocida como "hombres de cerillas" en los partidos. Oasis usó un vídeo animado de Lowry's Going to the Match para su sencillo, "The Masterplan".</p>
            <p>En el cine, la película titulada There's Only One Jimmy Grimble, trata sobre un niño cuyo sueño era jugar para el Manchester City. Los programas de televisión han tenido varios fanáticos ficticios del Manchester City que han sido retratados con diferentes gestos y personalidades.</p>
            <p>En 2010 se estrenó un largometraje sobre la temporada 2009-10 del Manchester City, llamado Blue Moon Rising.125​ La película trata sobre un grupo de fanáticos del Manchester City que viajan en un Renault Espace. donde detalla los altibajos durante toda la temporada del equipo. La película presenta imágenes exclusivas y entrevistas con fanáticos, jugadores y personal. La temporada documentó al City perdiendo por poco el cuarto lugar y el cupo para participar en la Liga de Campeones ante Tottenham Hotspur y siendo eliminado de la Copa de la Liga por el Manchester United en semifinales. Casualmente, la temporada siguiente hubo un cambio de suerte, donde el City lograría la clasificación a la Liga de Campeones y venciendo al United en la semifinales de la FA Cup para luego conquistar el título, terminando así con una sequía sin títulos desde hace 42 años.</p>
            <p>La película The Keeper, se centra en la vida del portero del City, Bert Trautmann.126​127​ Según los fanáticos, se sienten bien representados a lo largo de la película. Además, uno de los papeles principales fue interpretado por un aficionado del City, John Henshaw.</p>
          </AccordionBody>
        </AccordionItem>
      </Accordion>
    </div>
  );
}

export default Acordion;